
Neos:
  Demo:
    flickr:
      tagStreamUriPattern: 'http://api.flickr.com/services/feeds/photos_public.gne?format=json&nojsoncallback=1&tags=%s'
      userStreamUriPattern: 'http://api.flickr.com/services/feeds/photos_public.gne?format=json&nojsoncallback=1&id=%s'
  Form:
    yamlPersistenceManager:
      savePath: 'resource://Neos.Demo/Private/Form/'
    presets:
      bootstrap:
        title: 'Twitter bootstrap'
        parentPreset: default
        formElementTypes:
          'Neos.Form:Base':
            renderingOptions:
              layoutPathPattern: 'resource://Neos.Demo/Private/Templates/ContactForm/{@type}.html'
          'Neos.Form:FormElement':
            properties:
              elementClassAttribute: form-control
          'Neos.Form:MultiLineText':
            properties:
              elementClassAttribute: form-control
  Neos:
    userInterface:
      editPreviewModes:
        print:
          isEditingMode: false
          isPreviewMode: true
          fusionRenderingPath: print
          title: 'Neos.Demo:Main:editPreviewModes.print'
          position: 200
      translation:
        autoInclude:
          Neos.Demo:
            - Main
            - 'NodeTypes/*'
  ContentRepository:
    contentDimensions:
      language:
        label: 'Neos.Demo:Main:contentDimensions.language'
        icon: icon-language
        defaultValue: en_US
        values:
          en_US:
            label: 'English (US)'
            resolution:
              value: en
            specializations:
              en_UK:
                label: 'English (UK)'
                resolution:
                  value: uk
          de:
            label: German
            resolution:
              value: de
            specializations:
              nl:
                label: Dutch
                resolution:
                  value: nl
          fr:
            label: French
            resolution:
              value: fr
          da:
            label: Danish
            resolution:
              value: da
          lv:
            label: Latvian
            resolution:
              value: lv
